### ISSUE TITLE
Shorten boilerplate with luasnip snip_env

### ISSUE THREAD

**Issue by derekthecool** [ziontee113/luasnip-tutorial#2]
Hi,

Thanks for the great guide on luasnip. I've learned a great amount from your video and associated repo here.
I was getting really bugged by having to define all the locals to build snippets...

```lua
local ls = require("luasnip")
```
etc...

I found while reading this luasnip page about creating the [
lua snippets](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#lua) that you don't need to define them in each file.
That page links to this page with the exact spelling of each of the function names in the default setup you can use, see this 
[blob](https://github.com/L3MON4D3/LuaSnip/blob/69cb81cf7490666890545fef905d31a414edc15b/lua/luasnip/config.lua#L82-L104)

Here is my simple c.lua file as an example without any of the boilerplate from your example. I just wanted to show a very basic file and how nice it is to not have all the locals at the top.

```lua
---@diagnostic disable: undefined-global
local snippets = {
  s(
    {
      trig = 'clangf',
      descr = 'Comment string to disable clang formatting',
    },
    fmt(
      [[
      // clang-format off
      {}
      // clang-format on
      ]], { i(1) })
  ),

  s(
    {
      trig = 'strtok_ez',
      descr = 'Easily use strtok with a for loop'
    },
    fmt(
      [[
      for (char *p = strtok({}, ","); p != NULL; p = strtok(NULL, ","))
      {{
        returnValue += atoi(p);
      }}
      {}
      ]], { i(1, 'InputStringToParse'), i(2) })
  ),
}

local autosnippets = {}

return snippets, autosnippets
```

Since this repo goes along with the video I didn't want to just change your stuff, I just thought an issue discussion would be best.

**Comment by ziontee113** [comment]
Yes. You can shorten the boilerplate that way. I'm annoyed by them too. I'll probably make another LuaSnip related video in the future to polish the snippet creation process.

**Comment by derekthecool** [comment]
Sounds good, I mainly just wanted to pass along that info. I'll close this issue chat.
